# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: zwaveactions.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='zwaveactions.proto',
  package='zwave',
  syntax='proto3',
  serialized_pb=_b('\n\x12zwaveactions.proto\x12\x05zwave\"\x0f\n\rToggleRequest\"\x1e\n\x0bToggleReply\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32z\n\x0bZWaveAction\x12\x34\n\x06TurnOn\x12\x14.zwave.ToggleRequest\x1a\x12.zwave.ToggleReply\"\x00\x12\x35\n\x07TurnOff\x12\x14.zwave.ToggleRequest\x1a\x12.zwave.ToggleReply\"\x00\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_TOGGLEREQUEST = _descriptor.Descriptor(
  name='ToggleRequest',
  full_name='zwave.ToggleRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=44,
)


_TOGGLEREPLY = _descriptor.Descriptor(
  name='ToggleReply',
  full_name='zwave.ToggleReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='zwave.ToggleReply.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=46,
  serialized_end=76,
)

DESCRIPTOR.message_types_by_name['ToggleRequest'] = _TOGGLEREQUEST
DESCRIPTOR.message_types_by_name['ToggleReply'] = _TOGGLEREPLY

ToggleRequest = _reflection.GeneratedProtocolMessageType('ToggleRequest', (_message.Message,), dict(
  DESCRIPTOR = _TOGGLEREQUEST,
  __module__ = 'zwaveactions_pb2'
  # @@protoc_insertion_point(class_scope:zwave.ToggleRequest)
  ))
_sym_db.RegisterMessage(ToggleRequest)

ToggleReply = _reflection.GeneratedProtocolMessageType('ToggleReply', (_message.Message,), dict(
  DESCRIPTOR = _TOGGLEREPLY,
  __module__ = 'zwaveactions_pb2'
  # @@protoc_insertion_point(class_scope:zwave.ToggleReply)
  ))
_sym_db.RegisterMessage(ToggleReply)


try:
  # THESE ELEMENTS WILL BE DEPRECATED.
  # Please use the generated *_pb2_grpc.py files instead.
  import grpc
  from grpc.framework.common import cardinality
  from grpc.framework.interfaces.face import utilities as face_utilities
  from grpc.beta import implementations as beta_implementations
  from grpc.beta import interfaces as beta_interfaces


  class ZWaveActionStub(object):

    def __init__(self, channel):
      """Constructor.

      Args:
        channel: A grpc.Channel.
      """
      self.TurnOn = channel.unary_unary(
          '/zwave.ZWaveAction/TurnOn',
          request_serializer=ToggleRequest.SerializeToString,
          response_deserializer=ToggleReply.FromString,
          )
      self.TurnOff = channel.unary_unary(
          '/zwave.ZWaveAction/TurnOff',
          request_serializer=ToggleRequest.SerializeToString,
          response_deserializer=ToggleReply.FromString,
          )


  class ZWaveActionServicer(object):

    def TurnOn(self, request, context):
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')

    def TurnOff(self, request, context):
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')


  def add_ZWaveActionServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'TurnOn': grpc.unary_unary_rpc_method_handler(
            servicer.TurnOn,
            request_deserializer=ToggleRequest.FromString,
            response_serializer=ToggleReply.SerializeToString,
        ),
        'TurnOff': grpc.unary_unary_rpc_method_handler(
            servicer.TurnOff,
            request_deserializer=ToggleRequest.FromString,
            response_serializer=ToggleReply.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'zwave.ZWaveAction', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


  class BetaZWaveActionServicer(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    def TurnOn(self, request, context):
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)
    def TurnOff(self, request, context):
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)


  class BetaZWaveActionStub(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    def TurnOn(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      raise NotImplementedError()
    TurnOn.future = None
    def TurnOff(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      raise NotImplementedError()
    TurnOff.future = None


  def beta_create_ZWaveAction_server(servicer, pool=None, pool_size=None, default_timeout=None, maximum_timeout=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_deserializers = {
      ('zwave.ZWaveAction', 'TurnOff'): ToggleRequest.FromString,
      ('zwave.ZWaveAction', 'TurnOn'): ToggleRequest.FromString,
    }
    response_serializers = {
      ('zwave.ZWaveAction', 'TurnOff'): ToggleReply.SerializeToString,
      ('zwave.ZWaveAction', 'TurnOn'): ToggleReply.SerializeToString,
    }
    method_implementations = {
      ('zwave.ZWaveAction', 'TurnOff'): face_utilities.unary_unary_inline(servicer.TurnOff),
      ('zwave.ZWaveAction', 'TurnOn'): face_utilities.unary_unary_inline(servicer.TurnOn),
    }
    server_options = beta_implementations.server_options(request_deserializers=request_deserializers, response_serializers=response_serializers, thread_pool=pool, thread_pool_size=pool_size, default_timeout=default_timeout, maximum_timeout=maximum_timeout)
    return beta_implementations.server(method_implementations, options=server_options)


  def beta_create_ZWaveAction_stub(channel, host=None, metadata_transformer=None, pool=None, pool_size=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_serializers = {
      ('zwave.ZWaveAction', 'TurnOff'): ToggleRequest.SerializeToString,
      ('zwave.ZWaveAction', 'TurnOn'): ToggleRequest.SerializeToString,
    }
    response_deserializers = {
      ('zwave.ZWaveAction', 'TurnOff'): ToggleReply.FromString,
      ('zwave.ZWaveAction', 'TurnOn'): ToggleReply.FromString,
    }
    cardinalities = {
      'TurnOff': cardinality.Cardinality.UNARY_UNARY,
      'TurnOn': cardinality.Cardinality.UNARY_UNARY,
    }
    stub_options = beta_implementations.stub_options(host=host, metadata_transformer=metadata_transformer, request_serializers=request_serializers, response_deserializers=response_deserializers, thread_pool=pool, thread_pool_size=pool_size)
    return beta_implementations.dynamic_stub(channel, 'zwave.ZWaveAction', cardinalities, options=stub_options)
except ImportError:
  pass
# @@protoc_insertion_point(module_scope)
